# Default values for hostpath-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

strategyType: Recreate

## Location where PVs should be stored
hostpath: /mnt/hostpath

image:
  repository: quay.io/rimusz/hostpath-provisioner
  # Note that by default we use appVersion to get image tag
  # tag:
  pullPolicy: IfNotPresent

## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: true

  ## Set a StorageClass name
  name: hostpath

  ## Set reclaimPolicy for StorageClass
  ## More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming
  ## Options: Delete | Retain
  reclaimPolicy: Delete  

rbac:
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: default

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
